name: UltimateMeteorAnticheat
version: 1.0.0
main: net.meteorsmp.anticheat.UltimateMeoterAnticheat
api-version: '1.21'
author: MeteorSMP
description: Hybrid Grim and Vulcan anticheat system built for 1.21.11 Paper.
commands:
  anticheat:
    description: Main anticheat command.
    aliases: [ac]
    permission: meteorsmp.anticheat.admin
  acwhitelist:
    description: Manage anticheat whitelists.
    permission: meteorsmp.anticheat.admin
